import test from 'node:test';import assert from 'node:assert/strict';
import {CONFIG} from '../lib/config.js';import {initialState,runTick,report,eligibility,validateState} from '../lib/engine.js';import {parseBars,parseBook,loadMarket} from '../lib/market.js';import {updateLearning} from '../lib/learning.js';
const now=Date.UTC(2026,8,23,12,10),hour=3600000;
function bars(count=160){return Array.from({length:count},(_,i)=>({time:Math.floor(now/hour)*hour-(count-i)*hour,close:100*Math.pow(1.001,i-count+1),volume:10}))}
function asset(id='BTC/CAD'){return {id,currency:'CAD',assetClass:'crypto',bid:99.9,ask:100,bidSize:10,askSize:10,observedAt:now,receivedAt:now,quality:'live',source:'test fixture',minQty:.00001,minCost:1,precision:8,spreadBps:10,bars:bars()}}
const market=(...assets)=>({asOf:now,assets,errors:[]});
test('a paper entry reserves cash, respects caps, and pays fees',()=>{const s=runTick(initialState(now),market(asset(),asset('ETH/CAD')),now);assert.equal(s.trades.length,2);assert.ok(s.cash>=60);assert.ok(s.cash<=61);for(const p of Object.values(s.positions))assert.ok(p.cost<=20);assert.ok(s.fees>0);assert.ok(report(s,now).pnl<0)});
test('a repeated run and repeated completed bar never duplicate a buy',()=>{const s=runTick(initialState(now),market(asset()),now);assert.equal(runTick(s,market(asset()),now).trades.length,1);assert.equal(runTick(s,market(asset()),now+60000).trades.length,1)});
test('stale or future quotes cannot create paper trades',()=>{for(const t of [now-120001,now+5001]){const a=asset();a.observedAt=t;assert.equal(runTick(initialState(now),market(a),now).trades.length,0)}});
test('stale completed history blocks entries',()=>{const a=asset();a.bars=a.bars.map(b=>({...b,time:b.time-3*hour}));assert.equal(runTick(initialState(now),market(a),now).trades.length,0)});
test('wide spreads and unavailable metadata prevent buys',()=>{const a=asset();a.spreadBps=100;const s=runTick(initialState(now),market(a),now);assert.equal(s.trades.length,0);assert.equal(s.decisions[0].action,'BLOCKED');assert.equal(eligibility({...asset(),minQty:5},20).ok,false)});
test('options, futures and unconverted USD cannot trade',()=>{for(const kind of ['option','future','stock'])assert.equal(eligibility({...asset(),assetClass:kind},20).ok,false);assert.equal(eligibility({...asset(),currency:'USD'},20).ok,false)});
test('stops realize losses and preserve accounting',()=>{const s=runTick(initialState(now),market(asset()),now);const a={...asset(),bid:94,ask:94.1,observedAt:now+60000};const out=runTick(s,market(a),now+60000);assert.equal(out.trades.at(-1).side,'SELL');assert.equal(Object.keys(out.positions).length,0);assert.ok(out.realizedPnl<0);assert.ok(Math.abs(out.cash-100-out.realizedPnl)<1e-8)});
test('portfolio loss stop halts entries and exits available positions',()=>{const s=runTick(initialState(now),market(asset(),asset('ETH/CAD')),now);const out=runTick(s,market({...asset(),bid:80,ask:80.1,observedAt:now+60000},{...asset('ETH/CAD'),bid:80,ask:80.1,observedAt:now+60000}),now+60000);assert.equal(out.halted,true);assert.equal(Object.keys(out.positions).length,0);assert.ok(out.cash<95)});
test('outage leaves positions intact and reports stale equity',()=>{const s=runTick(initialState(now),market(asset()),now);const out=runTick(s,{assets:[],errors:[{id:'BTC/CAD',message:'outage'}]},now+180000);assert.equal(out.trades.length,1);assert.equal(report(out,now+180000).valuationStale,true);assert.equal(out.lastRun.status,'unavailable')});
test('paper buys never exceed top of book liquidity budget',()=>assert.equal(eligibility({...asset(),askSize:.01},20).ok,false));
test('shadow learner does not retrain on duplicate candles',()=>{const m=updateLearning(null,bars());const again=updateLearning(m,bars());assert.equal(again.samples,m.samples);assert.deepEqual(again.weights,m.weights)});
test('online learning is chronological and incremental',()=>{const b=bars();const first=updateLearning(null,b.slice(0,120));const incremental=updateLearning(first,b);assert.deepEqual(incremental.weights,updateLearning(null,b).weights);assert.ok(incremental.scored>0);assert.equal(incremental.latest.calibrated,false)});
test('unfinished Kraken candle is excluded; gaps rejected',()=>{const raw=bars(100).map(b=>[b.time/1000,b.close,b.close,b.close,b.close,0,10]);raw.push([Math.floor(now/hour)*hour/1000,1,1,1,999999,0,10]);const parsed=parseBars(raw,now);assert.equal(parsed.at(-1).close,100);assert.equal(parsed.length,100);raw[20][0]+=60;assert.throws(()=>parseBars(raw,now),/gapped/)});
test('invalid, crossed, stale books and offline instruments rejected',()=>{const meta={ordermin:'.001',costmin:'1',lot_decimals:8,status:'online'},book={bids:[['100','10',now/1000]],asks:[['101','10',now/1000]]};assert.ok(parseBook({id:'TEST'},book,meta,now));assert.throws(()=>parseBook({}, {...book,asks:[['99','10',now/1000]]},meta,now));assert.throws(()=>parseBook({},book,meta,now+120001));assert.throws(()=>parseBook({},book,{...meta,status:'offline'},now))});
test('provider outage is explicit and never replaced with fake data',async()=>{const r=await loadMarket({fetcher:async()=>{throw new Error('offline')}});assert.equal(r.assets.length,0);assert.equal(r.errors.length,2)});
test('malformed persisted state is rejected, not reset',()=>{assert.throws(()=>validateState({...initialState(),cash:NaN}));assert.throws(()=>validateState({...initialState(),cash:-1}));assert.throws(()=>validateState(null))});
