import {CONFIG,COVERAGE} from './config.js';
import {updateLearning,modelReport} from './learning.js';
export function initialState(now=Date.now()){return {schema:1,createdAt:now,updatedAt:now,initialCash:100,cash:100,positions:{},trades:[],decisions:[],equityHistory:[],models:{},lastBars:{},lastTradeAt:{},realizedPnl:0,fees:0,highWater:100,maxDrawdown:0,daily:{day:'',startEquity:100},halted:false,haltReason:null,lastRun:null,benchmark:{cash:100,btc:null},config:{...CONFIG}}}
export function validateState(s){if(!s||s.schema!==1||s.initialCash!==100||!Number.isFinite(s.cash)||s.cash<0||!Array.isArray(s.trades)||!s.positions||!s.models||!s.lastBars||!Number.isFinite(s.highWater))throw new Error('Invalid persisted account; refusing to reset it');for(const p of Object.values(s.positions))if(![p.qty,p.cost,p.entryPrice,p.lastBid].every(Number.isFinite)||p.qty<=0||p.cost<0||p.lastBid<=0)throw new Error('Invalid persisted position');return s}
export function trend(bars){if(bars.length<50)return {action:'hold',reason:'Need 50 completed hourly bars'};const prices=bars.map(b=>b.close);const avg=n=>prices.slice(-n).reduce((s,p)=>s+p,0)/n;const fast=avg(12),slow=avg(48),momentum=prices.at(-1)/prices.at(-25)-1;const returns=prices.slice(-25).slice(1).map((p,i)=>p/prices[prices.length-25+i]-1);const mean=returns.reduce((s,r)=>s+r,0)/returns.length;const vol=Math.sqrt(returns.reduce((s,r)=>s+(r-mean)**2,0)/(returns.length-1));if(vol>.015)return {action:'hold',reason:'Hourly volatility exceeds strategy limit',vol};if(fast>slow*1.001&&momentum>.01)return {action:'buy',reason:'12-hour average above 48-hour average; 24-hour momentum exceeds 1%',vol};if(fast<slow*.999)return {action:'sell',reason:'12-hour average below 48-hour average',vol};return {action:'hold',reason:'No eligible trend entry; cash is a valid position',vol}}
export function eligibility(asset,budget){if(!Number.isFinite(budget)||budget<=0)return {ok:false,reason:'No risk budget'};if(asset.currency!=='CAD')return {ok:false,reason:'Verified CAD conversion unavailable'};if(asset.assetClass==='future')return {ok:false,reason:'Futures margin and leverage disabled'};if(asset.assetClass==='option')return {ok:false,reason:'Options execution disabled pending contract and expiry engine'};if(asset.assetClass!=='crypto')return {ok:false,reason:'Only spot crypto enabled in this pilot'};const execution=asset.ask*(1+CONFIG.slippageBps/10000),qty=Math.floor(budget/(execution*(1+CONFIG.feeBps/10000))*10**asset.precision)/10**asset.precision;if(qty<asset.minQty||qty*execution<asset.minCost)return {ok:false,reason:'Below venue minimum quantity or cost'};if(qty>asset.askSize*.1)return {ok:false,reason:'Order exceeds 10% of displayed top-of-book liquidity'};return {ok:true,qty,execution,total:qty*execution*(1+CONFIG.feeBps/10000)}}
function value(s,assets){let missing=false;const positions=Object.entries(s.positions).map(([id,p])=>{const q=assets.find(a=>a.id===id);if(!q)missing=true;const bid=q?.bid??p.lastBid;const liquidation=bid*(1-CONFIG.slippageBps/10000)*p.qty*(1-CONFIG.feeBps/10000);return {...p,id,bid,liquidation,unrealizedPnl:liquidation-p.cost,stale:!q}});return {equity:s.cash+positions.reduce((sum,p)=>sum+p.liquidation,0),positions,stale:missing}}
function exit(s,a,reason,now){const p=s.positions[a.id];if(p.qty>a.bidSize*.1)return 'Exit blocked by displayed liquidity; position remains exposed';const execution=a.bid*(1-CONFIG.slippageBps/10000),gross=p.qty*execution,fee=gross*CONFIG.feeBps/10000,net=gross-fee,pnl=net-p.cost;s.cash+=net;s.fees+=fee;s.realizedPnl+=pnl;s.trades.push({id:`${now}-${a.id}-sell`,time:now,asset:a.id,side:'SELL',qty:p.qty,price:execution,fee,total:net,pnl,reason,source:a.source,quoteTime:a.observedAt,mode:'paper'});delete s.positions[a.id];s.lastTradeAt[a.id]=now;return 'Paper position closed'}
export function runTick(previous,market,now=Date.now()){
 const s=structuredClone(validateState(previous));
 if(s.lastRun&&now-s.lastRun.startedAt<45000)return s;
 // Never allow missing/invalid quotes to bypass the live-data gate.
 const assets=market.assets.filter(a=>a.quality==='live'&&a.currency==='CAD'&&Number.isFinite(a.bid)&&Number.isFinite(a.ask)&&a.bid>0&&a.ask>=a.bid&&now-a.observedAt>=-5000&&now-a.observedAt<=CONFIG.maxQuoteAgeMs&&a.bars?.length>=80&&now-(a.bars.at(-1).time+3600000)>=0&&now-(a.bars.at(-1).time+3600000)<=CONFIG.maxBarAgeMs);
 for(const a of assets){if(s.positions[a.id])s.positions[a.id].lastBid=a.bid;s.models[a.id]=updateLearning(s.models[a.id],a.bars)}
 let valuation=value(s,assets);const day=new Date(now).toISOString().slice(0,10);if(day!==s.daily.day)s.daily={day,startEquity:valuation.equity};
 if(!valuation.stale){s.highWater=Math.max(s.highWater,valuation.equity);s.maxDrawdown=Math.max(s.maxDrawdown,1-valuation.equity/s.highWater);if(1-valuation.equity/s.highWater>=CONFIG.maxDrawdownPct){s.halted=true;s.haltReason='5% equity drawdown stop — manual review required'}if(s.daily.startEquity-valuation.equity>=CONFIG.maxDailyLossCad){s.halted=true;s.haltReason='CAD $2 daily loss stop — manual review required'}}
 const decisions=[];
 for(const a of assets){const signal=trend(a.bars),bar=a.bars.at(-1).time,p=s.positions[a.id];let action='HOLD',reason=signal.reason;
  if(p){const move=a.bid/p.entryPrice-1;let cause=s.halted?s.haltReason:move<=-CONFIG.stopLossPct?'3% position stop':move>=CONFIG.takeProfitPct?'6% profit exit':signal.action==='sell'?'Trend reversal':null;if(cause){reason=exit(s,a,cause,now);action=s.positions[a.id]?'BLOCKED':'SELL'}}
  else if(signal.action==='buy'){
   if(s.halted){action='BLOCKED';reason=s.haltReason}
   else if(valuation.stale){action='BLOCKED';reason='Existing position lacks a fresh mark'}
   else if(s.lastBars[a.id]===bar){reason='Already evaluated this completed bar'}
   else if(now-(s.lastTradeAt[a.id]??0)<CONFIG.cooldownMs){reason='Six-hour trade cooldown'}
   else if(a.spreadBps>CONFIG.maxSpreadBps){action='BLOCKED';reason='Bid/ask spread exceeds 35 bps'}
   else{const exposure=Object.values(s.positions).reduce((n,p)=>n+p.cost,0);const budget=Math.min(CONFIG.maxPositionCad,CONFIG.maxExposureCad-exposure,s.cash-CONFIG.minCashCad);const order=eligibility(a,budget);if(!order.ok){action='BLOCKED';reason=order.reason}else{const fee=order.qty*order.execution*CONFIG.feeBps/10000;s.cash-=order.total;s.fees+=fee;s.positions[a.id]={qty:order.qty,cost:order.total,entryPrice:order.execution,openedAt:now,lastBid:a.bid};s.trades.push({id:`${now}-${a.id}-buy`,time:now,asset:a.id,side:'BUY',qty:order.qty,price:order.execution,fee,total:order.total,pnl:null,reason:signal.reason,source:a.source,quoteTime:a.observedAt,mode:'paper'});s.lastTradeAt[a.id]=now;action='BUY'}}
  }
  s.lastBars[a.id]=bar;decisions.push({time:now,asset:a.id,action,reason,barTime:bar,spreadBps:a.spreadBps});
 }
 for(const error of market.errors??[])decisions.push({time:now,asset:error.id,action:'UNAVAILABLE',reason:error.message});
 const btc=assets.find(a=>a.id==='BTC/CAD');if(btc&&!s.benchmark.btc){const price=btc.ask*(1+CONFIG.slippageBps/10000);s.benchmark.btc={qty:100/(price*(1+CONFIG.feeBps/10000)),startedAt:now,lastValue:100}}if(btc&&s.benchmark.btc)s.benchmark.btc.lastValue=s.benchmark.btc.qty*btc.bid*(1-CONFIG.slippageBps/10000)*(1-CONFIG.feeBps/10000);
 valuation=value(s,assets);s.updatedAt=now;s.lastRun={startedAt:now,finishedAt:Date.now(),status:assets.length===2?'ok':assets.length?'degraded':'unavailable',validAssets:assets.length,errors:market.errors??[]};s.decisions.push(...decisions);s.decisions=s.decisions.slice(-2000);s.trades=s.trades.slice(-10000);s.equityHistory.push({time:now,equity:valuation.equity,stale:valuation.stale,btc:s.benchmark.btc?.lastValue??null});s.equityHistory=s.equityHistory.slice(-4000);s.market={asOf:market.asOf,assets:assets.map(({bars,...a})=>({...a,barTime:bars.at(-1).time,trend:trend(bars)})),errors:market.errors??[]};return s;
}
export function report(s,now=Date.now()){
 validateState(s);const assets=(s.market?.assets??[]).filter(a=>now-a.observedAt<=CONFIG.maxQuoteAgeMs&&now-a.observedAt>=-5000);const v=value(s,assets);return {schema:1,mode:'paper',createdAt:s.createdAt,updatedAt:s.updatedAt,initialCash:100,currency:'CAD',cash:s.cash,equity:v.equity,valuationStale:v.stale,positions:v.positions,pnl:v.equity-100,realizedPnl:s.realizedPnl,unrealizedPnl:v.positions.reduce((n,p)=>n+p.unrealizedPnl,0),fees:s.fees,maxDrawdown:s.maxDrawdown,halted:s.halted,haltReason:s.haltReason,config:s.config,heartbeat:s.lastRun,workerAgeMs:s.lastRun?now-s.lastRun.startedAt:null,trades:s.trades.slice(-100),decisions:s.decisions.slice(-20).reverse(),history:s.equityHistory,models:Object.fromEntries(Object.entries(s.models).map(([k,m])=>[k,modelReport(m)])),benchmark:s.benchmark,market:s.market??null,coverage:COVERAGE,limitations:['Paper fills are estimates, not broker executions.','40 bps fee plus 10 bps adverse slippage on each leg; spreads also apply.','Stops execute only at the next successful poll and can lose more than their threshold.','The online learner remains shadow-only. No profit target or safety guarantee.']};
}
